<section class="content principal container-fluid d-flex align-items-center justify-content-between flex-column">
    <div class="row">
        <div class="col-md-12">
            <h1 class="welcome">Seja bem vindo João Vitor Martins de Siqueira</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p class="title">O que gostaria de fazer?</p>
        </div>
    </div>

    <div class="row cards">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-5 d-flex align-items-center justify-content-center">
                <article class="cardOption d-flex align-items-center justify-content-center flex-column">
                    <div class="d-flex align-items-center justify-content-center">
                        <span class="material-icons">note_add</span>
                        <h1>Fazer uma requisição</h1>
                    </div>
                    <hr>
                </article>
            </div>

            <div class="col-md-5 d-flex align-items-center justify-content-center">
                <article class="cardOption d-flex align-items-center justify-content-center flex-column">
                    <div class="d-flex align-items-center justify-content-center">
                        <span class="material-icons">history</span>
                        <h1>Olhar meu histórico</h1>
                    </div>
                    <hr>
                </article>
            </div>
        </div>

        <div class="row align-items-center justify-content-center">
            <div class="col-md-5 d-flex align-items-center justify-content-center">
                <article class="cardOption d-flex align-items-center justify-content-center flex-column">
                    <div class="d-flex align-items-center justify-content-center">
                        <span class="material-icons">settings</span>
                        <h1>Acessar as Configurações</h1>
                    </div>
                    <hr>
                </article>
            </div>
        </div>
    </div>
</section>