<div class="container">
    <section class="row introduction">
        <div class="col-md-5 d-flex justify-content-center align-items-start flex-column">
            <header class="d-flex justify-content-between flex-column">
                <h1>
                    Se você é habitante de Paranapanema/SP e dependente de medicamentos controlados, venha adquirir aqui sua receita digital de forma 100% gratuita.
                </h1>
                <a href="#">Acesse aqui</a>
            </header>
        </div>
        <figure class="col-md-7 imgPrincipal">
            <img src="img/principal.svg" alt="Imagem de um médico e seu paciente">
        </figure>
    </section>

    <section class="row whatIs justify-content-center">
        <header class="col-md-7">
            <h1>O que é?</h1>
            <p>
                A Receita Fácil Digital vai facilitar muito a sua vida, terá muita agilidade e praticidade para todos os setores, seja um paciente, um médico ou um farmacêutico. Além disso, a plataforma é totalmente gratuita para o seu uso.
            </p>
            <p>
                No entanto, ela é destinada apenas a cidadãos de Paranapanema/SP e dependentes de medicamentos controlados de uso contínuo, ou seja, sendo necessário uma receita médica para o seu uso.
            </p>
        </header>
    </section>
</div>

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" class="wave">
    <path fill="#222743" fill-opacity="1" d="M0,192L40,192C80,192,160,192,240,208C320,224,400,256,480,261.3C560,267,640,245,720,224C800,203,880,181,960,186.7C1040,192,1120,224,1200,224C1280,224,1360,192,1400,176L1440,160L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path>
</svg>

<div class="advantage">
    <div class="container">
        <section class="row">
            <div class="col-md-12">
                <h1>Vantagens</h1>

                <div class="d-flex justify-content-around align-items-center cards">
                    <article class="pacient cardAdvantage">
                        <h1>Paciente</h1>
                        <p>Acesse nosso site e tenha todas as vantagens abaixo:</p>
                        <ul>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Faça a requisição de sua prescrição médica de forma fácil e gratuita.
                            </li>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Receba-a em forma de um código QR por uma mensagem no seu celular, que pode ser facilmente utilizado.
                            </li>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Consiga a dispensa de seus medicamentos em uma farmácia parceira.
                            </li>
                        </ul>
                    </article>

                    <article class="doctor cardAdvantage">
                        <h1>Médico</h1>
                        <p>Acesse nosso site e tenha todas as vantagens abaixo:</p>
                        <ul>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Tenha acesso à todas as requisições feitas por pacientes em apenas um lugar.
                            </li>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Mais praticidade para a criação de novos receituários médicos por um meio digital.
                            </li>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Apenas um clique para fazer a emissão da receita ao cliente em poucos minutos, sendo apenas necessário uma assinatura digital.
                            </li>
                        </ul>
                    </article>
                    <article class="pharmaceutical cardAdvantage">
                        <h1>Farmacêutico</h1>
                        <p>Acesse nosso site e tenha todas as vantagens abaixo:</p>
                        <ul>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Tenha mais agilidade ao fazer a dispensa da receita médica, por meio de um leitor de código QR.
                            </li>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Armazene todas as receitas em apenas um só lugar.
                            </li>
                            <li>
                                <span class="material-icons-outlined">navigate_next</span>
                                Saiba de forma fácil, quantas receitas e medicamentos foram dispensados pela própria plataforma.
                            </li>
                        </ul>
                    </article>
                </div>
            </div>

        </section>
    </div>
</div>

<section class="row howWorks align-items-center flex-column">
    <div class="col-md-2">
        <h1>Como funciona</h1>
    </div>

    <div class="col-md-8">
        <article class="video d-flex justify-content-center align-items-center">
            <h1>Vídeo</h1>
        </article>
    </div>
</section>

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320" class="wave">
    <path fill="#222743" fill-opacity="1" d="M0,64L40,80C80,96,160,128,240,128C320,128,400,96,480,96C560,96,640,128,720,128C800,128,880,96,960,96C1040,96,1120,128,1200,122.7C1280,117,1360,75,1400,53.3L1440,32L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path>
</svg>

<div class="contact">
    <div class="container">
        <section class="row justify-content-center align-items-center">
            <div class="col-md-7">
                <h1>Fale conosco</h1>
                <p>Mande um e-mail para a gente, caso tenha alguma dúvida ou sugestão </p>

                <form action="#" method="post" class="d-flex align-items-center justify-content-center">
                    <span class="material-icons-outlined">mail</span>
                    <input type="text" placeholder="Digite seu E-mail">

                    <button type="submit">
                        <div class="d-flex justify-content-center align-items-center">
                            <span class="material-icons">
                                send
                            </span>
                        </div>
                    </button>
                </form>
            </div>
        </section>
    </div>
</div>