<header class="row">
    <div class="col-md-12">
        <h1>Crie sua conta aqui!</h1>
    </div>
</header>
<form action="/registrar" method="POST" class="row needs-validation">
    <?php foreach ($this->view->inputs as $input) { ?>
        <div class="row justify-content-center inputs">
            <div class="col-md-8 inputArea">
                <div class="input-group">
                    <label for="<?= $input['input'] ?>" class="input-group-text inputIcon <?= $input['input'] ?>Icon">
                        <span class="material-icons-outlined"><?= $input['icon'] ?></span>
                    </label>
                    <input type="<?= $input['type'] ?>" name="<?= $input['input'] ?>" class="form-control <?= $input['input'] ?>Input" id="<?= $input['input'] ?>" placeholder="<?= $input['placeholder'] ?>" required>

                </div>
                <div class="errorDiv text-start d-none <?= $input['input'] ?>Error">
                    <p class="ErrorMsg error text-danger <?= $input['input'] ?>ErrorMsg"></p>
                </div>
            </div>
        </div>
    <?php } ?>


    <div class="row inputs">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-8 inputArea">
                <div class="input-group">
                    <label for="password" class="input-group-text inputIcon passwordIcon">
                        <span class="material-icons-outlined">lock</span>
                    </label>
                    <input type="password" name="password" class="form-control passwordInput" id="password" placeholder="Senha" required>
                    <div class="viewPassDiv passwordIconView">
                        <div class="input-group-text d-flex justify-content-center align-items-center viewPass">
                            <span class="material-icons-outlined viewPassIcon">visibility</span>
                        </div>
                    </div>
                </div>
                <div class="errorDiv text-start d-none passwordError">
                    <p class="passwordErrorMsg error text-danger">Invalid</p>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12 row">
        <div class="col-md-12 d-flex justify-content-center align-items-center">
            <button type="submit" class="btnAction">Criar sua conta</button>
        </div>
    </div>
</form>