<div class="modal fade" id="changePasswordModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Esqueceu sua senha?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="/enviarCodigo" method="POST">
                <div class="modal-body">
                    <div class="row justify-content-center inputs">
                        <div class="col-md-8 inputArea inputModal">
                            <div class="input-group">
                                <label for="email" class="input-group-text inputIcon emailIcon emailModalIcon">
                                    <span class="material-icons-outlined">badge</span>
                                </label>
                                <input type="text" name="email" class="form-control emailInput emailModalInput emailInputModal" id="email" placeholder="Digite seu E-mail" required>
                            </div>
                            <div class="errorDiv text-start d-none emailError emailModalError">
                                <p class="error text-danger emailErrorMsg emailModalErrorMsg"></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btnModal" id="btnChangePassword">Mudar minha senha</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="VerifyCodeModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Código enviado!</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="/verificarCodigo" method="POST">
                <div class="modal-body">
                    <p>Foi enviado um código para o e-mail informado</p>
                    <div class="row justify-content-center inputs">
                        <div class="col-md-8 inputArea inputModal">
                            <div class="input-group">
                                <label for="inputCode" class="input-group-text inputIcon codeIcon">
                                    <span class="material-icons-outlined">lock</span>
                                </label>
                                <input type="text" name="Code" class="form-control codeInput codeInputModal" id="inputCode" placeholder="Digite seu código aqui" required>
                            </div>
                            <div class="errorDiv text-start d-none codeError">
                                <p class="error text-danger codeErrorMsg"></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btnModal" id="btnVerifyCode">Verificar código</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="newPasswordModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Digite sua nova senha</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="/mudarSenha" method="POST">
                <div class="modal-body">
                    <div class="row justify-content-center inputs">
                        <div class="col-md-8 inputArea inputModal">
                            <div class="input-group">
                                <label for="newPassword" class="input-group-text inputIcon passwordModalIcon">
                                    <span class="material-icons-outlined">lock</span>
                                </label>
                                <input type="password" name="newPassword" class="form-control passwordInput passwordModalInput passwordModalInputModal" id="newPassword" placeholder="Digite sua nova senha" required>
                                <div class="viewPassDiv passwordModalIconView">
                                    <div class="input-group-text d-flex justify-content-center align-items-center viewPass">
                                        <span class="material-icons-outlined viewPassIcon">visibility</span>
                                    </div>
                                </div>
                            </div>
                            <div class="errorDiv text-start d-none passwordModalError">
                                <p class="error text-danger passwordModalErrorMsg"></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btnModal" id="btnNewPassword">Mudar senha</button>
                </div>
            </form>
        </div>
    </div>
</div>