<div class="modal fade" id="detailPrescription">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Receita número </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="row justify-content-between align-items-center">
                    <div class="col-sm-5 d-flex flex-column">
                        <label for="pacientName" class="inputLabel">Nome do Paciente</label>
                        <input type="text" class="pacientName" disabled>
                    </div>
                    <div class="col-sm-5 d-flex flex-column">
                        <label for="pacientCPF" class="inputLabel">CPF do Paciente</label>
                        <input type="text" class="pacientCPF" disabled>
                    </div>
                </div>

                <div class="row justify-content-between align-items-center">
                    <div class="col-sm-5 d-flex flex-column">
                        <label for="issueDate" class="inputLabel">Data de Emissão</label>
                        <input type="text" class="issueDate" disabled>
                    </div>
                    <div class="col-sm-5 d-flex flex-column">
                        <label for="doctorName" class="inputLabel">Nome do Médico</label>
                        <input type="text" class="doctorName" disabled>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 d-flex flex-column">
                        <label for="medicinesList" class="inputLabel">Medicamentos</label>
                        <textarea class="medicinesList text-justify" disabled rows=4></textarea>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>