<div class="modal fade" id="template">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title title"></h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="formTemplate row justify-content-center" id="formTemplate" method="POST">
                <div class="modal-body row justify-content-center">
                    <input type="hidden" name="templateId" class="templateId">
                    <div class="row justify-content-center inputs">
                        <div class="col-md-8 inputArea inputModal">
                            <div class="input-group">
                                <label for="templateNameModal" class="input-group-text inputIcon templateNameModalIcon">
                                    <span class="material-icons-outlined">content_paste</span>
                                </label>
                                <input type="text" name="templateName" class="form-control templateNameModalInput templateNameModalInputModal" id="templateNameModal" placeholder="Digite o nome para o modelo" required>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="row justify-content-center">
                                <div class="errorDiv text-start d-none templateNameModalError">
                                    <p class="ErrorMsg error text-danger templateNameModalErrorMsg"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <fieldset class="medicinesData row justify-content-center mb-4" form="formTemplate" id="medicinesData">
                        <legend>Medicamentos</legend>
                        <fieldset class="medicinesData medicineData col-11 row justify-content-center mb-2" form="formTemplate">
                            <span class="material-icons-outlined removeMedicine text-end text-danger hidden">close</span>
                            <legend>Medicamento</legend>
                            <div class="medicines row justify-content-center">
                                <div class="medicine row justify-content-center">
                                    <div class="inputs row justify-content-center">
                                        <div class="input col-md-5 col-10 d-flex flex-column mb-1">
                                            <label for="medicine">Medicamento:*</label>
                                            <input type="text" name="medicineName[]" class="medicineNameInput" id="medicineName" required>

                                            <div class="errorDiv text-start d-none medicineNameError">
                                                <p class="ErrorMsg error text-danger medicineNameErrorMsg"></p>
                                            </div>
                                        </div>
                                        <div class="offset-md-1 col-md-5 col-10 mb-1">
                                            <div class="row justify-content-between">
                                                <div class="input col-md-4 col-4 d-flex flex-column">
                                                    <label for="medicine">Dosagem:*</label>
                                                    <input type="text" name="medicineSize[]" class="medicineSizeInput" id="medicineSize" required>

                                                    <div class="errorDiv text-start d-none medicineSizeError">
                                                        <p class="ErrorMsg error text-danger medicineSizeErrorMsg"></p>
                                                    </div>
                                                </div>
                                                <div class="input col-md-6 col-6 d-flex flex-column">
                                                    <label for="medicine">Frequência:*</label>
                                                    <input type="text" name="medicineFrequency[]" class="medicineFrequencyInput" id="medicineFrequency" required>


                                                    <div class="errorDiv text-start d-none medicineFrequencyError">
                                                        <p class="ErrorMsg error text-danger medicineFrequencyErrorMsg"></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div class="input row col-md-11 col-10 flex-column mt-2">
                                        <label for="medicine">Observação:</label>
                                        <input type="text" name="medicineObs[]" class="medicineObsInput" id="medicineObs">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </fieldset>

                    <div class="row btns">
                        <div class="row justify-content-center mb-3">
                            <button type="button" class="addMedicine col-md-9 col-10 d-flex align-items-center justify-content-center">
                                <span class="material-icons-outlined">add</span>
                                Adicionar Medicamento
                            </button>
                        </div>
                    </div>
                </div>
                <div class="modal-footer row justify-content-center align-items-center">
                    <div class="col-md-5 col-10">
                        <button type="button" class="btnDeleteTemplate">Excluir modelo</button>
                    </div>
                    <div class="col-md-5 col-10">
                        <button type="submit" class="btnTemplate">Salvar modelo</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>