<div class="modal fade" id="saveTemplate">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title">Salvar modelo</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" class="formSaveTemplate">
                <div class="modal-body">
                    <div class="row justify-content-center inputs">
                        <div class="col-md-8 inputArea inputModal">
                            <div class="input-group">
                                <label for="templateName" class="input-group-text inputIcon templateNameIcon templateNameModalIcon">
                                    <span class="material-icons-outlined">content_paste</span>
                                </label>
                                <input type="text" name="templateName" class="form-control templateNameInput templateNameModalInput" id="templateName" placeholder="Digite o nome para o modelo" required>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="row justify-content-center">
                                <div class="errorDiv text-start d-none templateNameError templateNameModalError">
                                    <p class="ErrorMsg error text-danger templateNameErrorMsg templateNameModalErrorMsg"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <button type="submit" class="btnSaveTemplate">Salvar modelo</button>
                </div>
            </form>
        </div>
    </div>
</div>