<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Receita Fácil Digital</title>

    <link rel="stylesheet" href="css/libraries/icons.css">
    <link rel="stylesheet" href="css/libraries/bootstrap.css">
    <link rel="stylesheet" href="css/userHeader.css">
    <link rel="stylesheet" href="css/<?= $this->view->page ?>.css">
</head>

<body>
    <div class="container-fluid p-4">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light col-md-3 d-flex justify-content-between align-items-start">

                <button class="navbar-toggler iconToggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse navbarHeader" id="navbarTogglerDemo02">
                    <ul class="navbar-nav d-flex flex-column justify-content-between">
                        <div class="headerMenu d-flex justify-content-between flex-column">
                            <li class="nav-item">
                                <a href="/plataforma/perfil" id="account" class="d-flex align-items-center">
                                    <span class="material-icons">account_circle</span>
                                    <span class="navbarCollapse">João Vitor Martins de Siqueira</span>
                                </a>
                            </li>
                            <div class="headerMenuOptions d-flex justify-content-between flex-column">
                                <li class="nav-item navItemSm">
                                    <a href="/plataforma" id="home" class="selected headerMenuOption d-flex align-items-center">
                                        <span class="material-icons">home</span>
                                        <span class="navbarCollapse">Principal</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/plataforma/acao" id="action" class="headerMenuOption d-flex align-items-center">
                                        <span class="material-icons">note_add</span>
                                        <span class="navbarCollapse">Fazer uma requisição</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="/plataforma/historico" id="history" class="headerMenuOption d-flex align-items-center">
                                        <span class="material-icons">history</span>
                                        <span class="navbarCollapse">Histórico de receitas</span>
                                    </a>
                                </li>
                                <li class="nav-item navItemMd">
                                    <a href="/plataforma/configuracoes" id="settings" class="headerMenuOption d-flex align-items-center">
                                        <span class="material-icons">settings</span>
                                        <span class="navbarCollapse">Configurações</span>
                                    </a>
                                </li>
                            </div>
                        </div>
                        <li class="nav-item nav-itemLogin">
                            <a href="/plataforma/sair" class="login d-flex align-items-center">
                                <span class="material-icons">logout</span>
                                <span class="navbarCollapse">Sair</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="col-md-9 content">
                <?= $this->content(); ?>
            </div>
        </div>
    </div>

    <script src="js/libraries/jquery.js"></script>
    <script src="js/libraries/bootstrap.js"></script>
    <script src="js/layoutUser.js"></script>
</body>