<div class="row mb-5">
    <div class="col-md-12 text-center">
        <h1 class="welcome">Seus modelos</h1>
    </div>
</div>

<div class="row">
    <form action="#" method="POST" class="row justify-content-center align-items-center formSearchTemplates">
        <div class="col-md-4 inputArea">
            <div class="input-group d-flex align-items-center">
                <label for="templateName" class="input-group-text inputIcon">
                    <span class="material-icons-outlined">content_paste_search</span>
                </label>
                <input type="text" name="templateName" class="form-control templateNameInput" id="templateName" placeholder="Nome do modelo" required>
            </div>
        </div>
        <div class="col-md-2 offset-md-1">
            <button class="searchBtnTemplates d-flex align-items-center justify-content-center">
                <span class="material-icons-outlined">search</span>
                Buscar
            </button>
        </div>
    </form>
</div>
<div class="row justify-content-center">
    <div class="col-md-7 col-12 mt-4">
        <button class="createTemplateBtn d-flex align-items-center justify-content-center">
            <span class="material-icons-outlined">add</span>
            Criar modelo
        </button>
    </div>
</div>
<div class="modal-body row modalTemplateSelectBody justify-content-center">
    <h1 class="messageTemplateSelect text-center mt-2"></h1>

    <div class="templatesCards row justify-content-around col-11 mt-2"></div>
</div>